### ISSUE TITLE
Display message and ShownOnMap race condition

### ISSUE THREAD

**Issue by teamagam3** [teamagam/GimelGimel#157]
There is bug in **MessagesViewModel** and **DisplayMessagesInteractor**.
The **DisplayMessagesInteractor** makes subscription request to two repositories.: **DisplayedEntitiesRepository** and **MessagesRepository**.

When new message arrives, the view model insert new item to the random accessor, but also wants to update if the geo entitiy is shown on the map.

The race condition is right here. The function "**messageShownOnMap()**" in the displayer could be invoked before inserting the related item to the random accessor.

**Comment by teamagam5** [comment]
Resolved in alerts feature
