### ISSUE TITLE
Viewer's last ViewerCamera

### ISSUE THREAD

**Issue by teamagam5** [teamagam/GimelGimel#161]
Currently the view-model of the viewer subscribes to an observable given by the viewer, and maintains a private field in order to save the last ViewerCamera when onStop is called.
We would like to have a synchronized method to get the ViewerCamera but that isn't possible. Instead, there should be a method called getLastViewerCamera that will be used when onStop is invoked. The implementation can be just the same as now but encapsulated into the viewer (the viewer will save its state into a private field but will expose it only by the mentioned method).

**Comment by BarAgam** [comment]
resolved while migrating to ESRI MapView
